#### Exercícios para praticar - Dataframe: TITANIC

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("Titanic-Dataset.csv")

#### Exercício 1

  - Carregue o dataset e descubra o tamanho dele.

In [3]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [4]:
df.shape

(891, 12)

#### Exercício 2
   - Visualize as primeiras 8 linhas.

In [5]:
df.head(8)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S

#### Exercício 3
   - Visualize as últimas 6 linhas.

In [6]:
df.tail(6)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.125,NaN,Q
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.450,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.750,NaN,Q

#### Exercício 4
  
  - Descubra os nomes de todas as colunas.

In [7]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [8]:
df["Embarked"].unique()

array(['S', 'C', 'Q', nan], dtype=object)

#### Exercício 5

  - Verifique as informações gerais do dataset e responda nos comentários quantas colunas são numéricas e quantas são texto.

In [ ]:
df.info()
# numericas (float + int): 7
# Texto: 5

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

#### Exercício 6

  - Verifique se há valores nulos e quantos tem em cada coluna. Responda nos comentários quais colunas têm mais nulos.

In [47]:
df.isnull().sum()
# 0 Colunas.

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

#### Exercício 7

   - Descubra quantos valores únicos tem cada coluna e liste os valores únicos da coluna Sex.

In [17]:
df.describe().nunique()

PassengerId    6
Survived       5
Pclass         6
Age            8
SibSp          6
Parch          5
Fare           8
dtype: int64

In [23]:
df["Sex"].unique()

array(['male', 'female'], dtype=object)

####  Exercício 8

  - Mostre as estatísticas gerais do dataset formatadas com 2 casas decimais.

In [29]:
with pd.option_context("float_format", "{:.2f}".format):
    display(df.describe())

       PassengerId  Survived  Pclass    Age  SibSp  Parch   Fare
count       891.00    891.00  891.00 714.00 891.00 891.00 891.00
mean        446.00      0.38    2.31  29.70   0.52   0.38  32.20
std         257.35      0.49    0.84  14.53   1.10   0.81  49.69
min           1.00      0.00    1.00   0.42   0.00   0.00   0.00
25%         223.50      0.00    2.00  20.12   0.00   0.00   7.91
50%         446.00      0.00    3.00  28.00   0.00   0.00  14.45
75%         668.50      1.00    3.00  38.00   1.00   0.00  31.00
max         891.00      1.00    3.00  80.00   8.00   6.00 512.33

#### Exercício 9

  - Analise somente as colunas de texto do dataset usando describe e select_dtypes.

In [30]:
#Describe
df.describe(exclude="number")

                           Name   Sex  Ticket    Cabin Embarked
count                       891   891     891      204      889
unique                      891     2     681      147        3
top     Braund, Mr. Owen Harris  male  347082  B96 B98        S
freq                          1   577       7        4      644

In [32]:
#Select_dtype
df.select_dtypes("object").head(15)

,Name,Sex,Ticket,Cabin,Embarked
0,"Braund, Mr. Owen Harris",male,A/5 21171,NaN,S
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,PC 17599,C85,C
2,"Heikkinen, Miss. Laina",female,STON/O2. 3101282,NaN,S
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,113803,C123,S
4,"Allen, Mr. William Henry",male,373450,NaN,S
5,"Moran, Mr. James",male,330877,NaN,Q
6,"McCarthy, Mr. Timothy J",male,17463,E46,S
7,"Palsson, Master. Gosta Leonard",male,349909,NaN,S
8,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,347742,NaN,S
9,"Nasser, Mrs. Nicholas (Adele Achem)",female,237736,NaN,C
10,"Sandstrom, Miss. Marguerite Rut",female,PP 9549,G6,S
11,"Bonnell, Miss. Elizabeth",female,113783,C103,S
12,"Saundercock, Mr. William Henry",male,A/5. 2151,NaN,S
13,"Andersson, Mr. Anders Johan",male,347082,NaN,S
14,"Vestrom, Miss. Hulda Amanda Adolfina",female,350406,NaN,S

#### Exercício 10 — Desafio

 - Faça a checagem básica completa do dataset e escreva um comentário resumindo:

   - Quantas linhas e colunas?
   
   - Quais colunas têm valores nulos?
   
   - Quantos passageiros são homens e quantos são mulheres?
   
   - Quantas classes de cabine existem?

In [34]:
#linha e coluna
df.shape

(891, 12)

In [35]:
#Valores nulos
df.describe().isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Age            0
SibSp          0
Parch          0
Fare           0
dtype: int64

In [40]:
df[df["Sex"] == "male"].nunique().sum()

2066

In [42]:
df[df["Sex"] == "female"].nunique().sum()

1192

In [ ]:
df["Cabin"].nunique()

147

In [48]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

#### Erros cometidos

Exercício 6 — ⚠️ Usou df.describe().isnull().sum() — isso verifica nulos nas estatísticas, não no dataset!

  - Nesta primeira correção, pude perceber que cometi um erro. Describe() é usado para verificar as estatisticas em geral. Quando o Describe é utilizado, automaticamente ele já retira os valores nulos do dataframe. Por isso em meu caso deu errado. 

  - O certo é usar o df.isnull().sum()

In [50]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

Exercício 7 — ⚠️ Usou df.describe().nunique() — mesmo erro do 6! O correto é df.nunique()

  - Neste exercicio, o exercicio A está incorreto, pois usei o describe(). Como dito em cima, o describe é utilizado para gerar as estatisticas do nosso DF. 

  - O uso correto é utilizar somente a variavel DF.

In [52]:
df.nunique().sum()

2970

Exercício 10 — ⚠️ Mesmo erro nos nulos. E pra contar homens/mulheres o correto seria:

   - Na penultima pergunta, mesmo erro que nos exercicios 6°, 7°. Mas neste, mais para frente será discutido sobre o método value_counts()

In [53]:
df["Sex"].value_counts()

Sex
male      577
female    314
Name: count, dtype: int64